MODULE = hardware

SRCS = memory.cpp timer.cpp uart.cpp \
 	fast-bus.cpp probe.cpp adc.cpp dac.cpp tdf2de.cpp \
	dc_motor.cpp de2tdf.cpp fp_conversions_helpers.cpp adc_dac_helpers.cpp
TARGET = libhardware.a

ROOT=../
WITH_SDL=yesPlease
include $(ROOT)/Makefile.common
